# Generated by Django 3.2 on 2021-04-24 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_assign_app', '0002_alter_jobads_employer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employers',
        ),
    ]
