# Generated by Django 3.2 on 2021-04-24 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_assign_app', '0004_delete_appliedapplicants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobAds',
            new_name='jobAd',
        ),
    ]
