# Generated by Django 3.2.2 on 2021-05-13 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_assign_app', '0005_rename_jobads_jobad'),
    ]

    operations = [
        migrations.CreateModel(
            name='employer',
            fields=[
                ('emplo_id', models.AutoField(auto_created=True, help_text='Primary key for table', primary_key=True, serialize=False, unique=True)),
                ('emplo_comname', models.CharField(help_text='Company Name', max_length=100)),
                ('emplo_number', models.CharField(help_text='Employer Number', max_length=10, unique=True)),
                ('emplo_email', models.CharField(help_text='Email Address', max_length=100)),
                ('emplo_occupation', models.CharField(help_text='Employer Occupation', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobad',
            name='adNumber',
        ),
        migrations.RemoveField(
            model_name='jobad',
            name='employer',
        ),
        migrations.AddField(
            model_name='jobad',
            name='jobId',
            field=models.AutoField(auto_created=True, default=100, help_text='Primary key for table', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='jobad',
            name='salary',
            field=models.IntegerField(help_text='Offered salary for the job', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_contact_no',
            field=models.CharField(help_text='Contact number', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.AutoField(auto_created=True, default=500, help_text='Primary key for table', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='dateAdded',
            field=models.DateTimeField(auto_now_add=True, help_text='Date added to site'),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='jobDescription',
            field=models.CharField(help_text='Job Description', max_length=400),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='jobTitle',
            field=models.CharField(help_text='Job Title', max_length=100),
        ),
        migrations.CreateModel(
            name='AppliedApplicants',
            fields=[
                ('appliedId', models.AutoField(auto_created=True, default=8000, primary_key=True, serialize=False, unique=True)),
                ('dateApplied', models.DateTimeField(auto_now_add=True)),
                ('moneyOffered', models.DecimalField(decimal_places=0, default=0, max_digits=7)),
                ('Employee_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_assign_app.employee')),
                ('ad_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_assign_app.jobad')),
            ],
        ),
    ]
