# Generated by Django 3.2.2 on 2021-05-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_assign_app', '0006_auto_20210513_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedapplicants',
            name='Add_duration',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Duration in Weeks', max_digits=7),
        ),
        migrations.AlterField(
            model_name='appliedapplicants',
            name='appliedId',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.AutoField(auto_created=True, help_text='Primary key for table', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='jobId',
            field=models.AutoField(auto_created=True, help_text='Primary key for table', primary_key=True, serialize=False, unique=True),
        ),
    ]
